### ISSUE TITLE
Android target crashes

### ISSUE THREAD

**Issue by ash086** [hyperfiction/HypMedias#2]
Not working for me on android target:

E/hxcpp   ( 9174): GetLocalAllocMT - requesting memory from unregistered thread!
F/libc    ( 9174): Fatal signal 11 (SIGSEGV) at 0x00000000 (code=1), thread 9174 (n.hypmediasdemo)

When I removed event dispatching code all starts to work

**Comment by shoebox** [comment]
Hi,

it is due to Hxcpp 3.0.

I'm not sure, but i think than hxcpp 3.1 fix the bug.

If not it requires to edit the externalinterface, by surrounding the val_callX calls into this:

int top = 0;
gc_set_top_of_stack(&top,true);
gc_exit_blocking();
//val_callX()
gc_enter_blocking();    

Then recompile the android so

**Comment by ash086** [comment]
Tried with latest hxcpp 3.1.21, problem still exits
After applying given patch and recompiling so all starts to work
Thanks

**Comment by shoebox** [comment]
Good to know, if you could make a pull request with the fix, this way i wouldn't have to redo it myself.
thanks
